Vagrant.configure("2") do |config|
  config.vm.box = "clincha/proxmox-ve-8"
  config.vm.box_version = "1.2.1"
  config.vm.provider "virtualbox" do |vb|
    vb.memory = "8192"
    vb.cpus = "4"
    vb.customize ["modifyvm", :id, "--nicpromisc1", "allow-all"]
    vb.customize ["modifyvm", :id, "--nicpromisc2", "allow-all"]
  end
  config.vm.network "forwarded_port", id: "proxmox_web_gui", host: 8006, guest: 8006, host_ip: "0.0.0.0", guest_ip: "10.0.2.15"
  config.vm.network "forwarded_port", id: "ssh", host: 2222, guest: 22, host_ip: "0.0.0.0", guest_ip: "10.0.2.15"

  config.vm.network "public_network", bridge: "eth0" #, auto_config: false

  config.ssh.username = 'root'
  config.ssh.password = 'vagrant'
  config.ssh.insert_key = 'true'

  config.vm.provision "file", source: "scripts/interfaces", destination: "/etc/network/interfaces"
#   config.vm.provision "shell", path: "scripts/setup-bridge.sh"

#   config.vm.synced_folder "./iso", "/var/lib/vz/template/iso"
end