name: "Deploy Vagrant Server"
on:
  push:
    branches:
      - '**'
  workflow_dispatch:
env:
  VIRTUALBOX_VERSION: "7.0"
  VAGRANT_VERSION: "2.4.1-1"
  UBUNTU_VERSION: "24.04.1"
jobs:
  tests:
    strategy:
      fail-fast: false
      matrix:
        proxmox_version: [ 7, 8 ]
    runs-on: ubuntu-22.04
    steps:
      - name: "Checkout code"
        uses: actions/checkout@v4

      - name: "Install VirtualBox"
        run: |
          wget -O- https://www.virtualbox.org/download/oracle_vbox_2016.asc | sudo gpg --dearmor -o /usr/share/keyrings/oracle-virtualbox-2016.gpg
          echo "deb [arch=amd64 signed-by=/usr/share/keyrings/oracle-virtualbox-2016.gpg] https://download.virtualbox.org/virtualbox/debian $(lsb_release -cs) contrib" | sudo tee /etc/apt/sources.list.d/virtualbox.list
          sudo apt-get -qq update 
          sudo apt-get -qq install virtualbox-${{ env.VIRTUALBOX_VERSION }}

      - name: "Install Vagrant"
        run: |
          wget -O- https://apt.releases.hashicorp.com/gpg | sudo gpg --dearmor -o /usr/share/keyrings/hashicorp-archive-keyring.gpg
          echo "deb [signed-by=/usr/share/keyrings/hashicorp-archive-keyring.gpg] https://apt.releases.hashicorp.com $(lsb_release -cs) main" | sudo tee /etc/apt/sources.list.d/hashicorp.list
          sudo apt-get update -qq 
          sudo apt-get -qq install vagrant=${{ env.VAGRANT_VERSION }}

      - name: "Load the Ubuntu ISO into the Vagrant box"
        working-directory: vagrant/proxmox-${{ matrix.proxmox_version }}
        run: |
          mkdir iso
          sudo wget -q --content-disposition -P ./iso https://releases.ubuntu.com/${{ env.UBUNTU_VERSION }}/ubuntu-${{ env.UBUNTU_VERSION }}-live-server-amd64.iso

      - name: "Start Vagrant box"
        working-directory: vagrant/proxmox-${{ matrix.proxmox_version }}
        run: |
          sudo vagrant up --no-tty

      - name: "Initialize Packer"
        working-directory: packer
        run: |
          packer init .

      - name: "Build template with Packer"
        working-directory: packer
        env:
          PACKER_LOG: 1
          PACKER_LOG_PATH: /tmp/logs/packer-proxmox-${{ matrix.proxmox_version }}.log
        run: |
          mkdir /tmp/logs
          nohup packer build \
          -var "ssh_password=${{ secrets.ANSIBLE_PASSWORD }}" \
          . &
          echo "Packer build started, sleeping."
          sleep 10

      - name: "Read the terminal output"
        working-directory: vagrant/proxmox-${{ matrix.proxmox_version }}
        run: |
          sudo vagrant ssh -c "sudo qm terminal 100" > /tmp/logs/packer-serial-${{ matrix.proxmox_version }}.log

      - name: "Change permissions of the log files"
        if: always()
        run: |
          sudo chown $USER:$USER /tmp/logs

      - name: "Upload log files"
        if: always()
        uses: actions/upload-artifact@v4.4.0
        with:
          name: packer-proxmox-${{ matrix.proxmox_version }} logs
          path: /tmp/logs
