on:
  push:
    branches:
      - '**'
env:
  GO_VERSION: 1.22.5
  VIRTUALBOX_VERSION: 7.0
  VAGRANT_VERSION: 2.2.19
jobs:
  test:
    runs-on: ubuntu-22.04
    steps:
      - name: "Checkout code"
        uses: actions/checkout@v4
      - name: "Install VirtualBox"
        run: |
          wget -O- https://www.virtualbox.org/download/oracle_vbox_2016.asc | sudo gpg --dearmor -o /usr/share/keyrings/oracle-virtualbox-2016.gpg
          echo "deb [arch=amd64 signed-by=/usr/share/keyrings/oracle-virtualbox-2016.gpg] https://download.virtualbox.org/virtualbox/debian $(lsb_release -cs) contrib" | sudo tee /etc/apt/sources.list.d/virtualbox.list
          sudo apt-get update && sudo apt-get install virtualbox-7.0

      - name: "Install Vagrant"
        run: |
          wget -O- https://apt.releases.hashicorp.com/gpg | sudo gpg --dearmor -o /usr/share/keyrings/hashicorp-archive-keyring.gpg
          echo "deb [signed-by=/usr/share/keyrings/hashicorp-archive-keyring.gpg] https://apt.releases.hashicorp.com $(lsb_release -cs) main" | sudo tee /etc/apt/sources.list.d/hashicorp.list
          sudo apt-get update && sudo apt-get install vagrant

      - name: "Install Go"
        uses: actions/setup-go@v5
        with:
          go-version: 1.22.5

      - name: "Restore Vagrant box"
        id: restore-vagrant-box
        uses: 'actions/cache/restore@v4.0.2'
        with:
          path: vagrant
          key: ${{ runner.os }}-${{ hashFiles('vagrant/Vagrantfile') }}

      - name: "Provision Vagrant box"
        if: steps.restore-vagrant-box.outputs.cache-hit != 'true'
        working-directory: vagrant
        run: |
          sudo vagrant provision

      - name: "Save Vagrant box"
        id: cache-vagrant-box
        uses: 'actions/cache/save@v4.0.2'
        with:
          path: vagrant
          key: ${{ runner.os }}-${{ hashFiles('vagrant/Vagrantfile') }}

      - name: "Start Vagrant box"
        working-directory: vagrant
        run: |
          sudo vagrant up

      - name: "Load the Ubuntu ISO into the Vagrant box"
        working-directory: vagrant
        run: |
          sudo vagrant ssh -c "sudo wget -O /var/lib/vz/template/iso http://releases.ubuntu.com/20.04/ubuntu-20.04.3-live-server-amd64.iso"

      - name: "Run tests"
        working-directory: pkg/proxmox
        run: |
          go test -v

      - name: "Tear down Vagrant box"
        working-directory: vagrant
        run: |
          sudo vagrant destroy -f
